{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-data
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataDirSize | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  volumeMode: {{ .Values.persistence.volumeMode | quote }}
  volumeName: {{ .Chart.Name }}-data
  {{- end }}
