# Common Labels
labels:
  app: "mgramseva-digit-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "mgramseva-digit-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "mgramseva-digit-ui"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/mgramseva-digit-ui/"
  readinessProbePath: "/mgramseva-digit-ui/"

namespace: mgramseva    
extraVolumes: |
  - name: js-injection
    configMap:
      name: mgramseva-digit-ui-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf

env:          
  - name: REACT_APP_STATE_LEVEL_TENANT_ID
    value: {{ index .Values "react-app-state-level-tenant-id" | quote }}
  - name: REACT_APP_PROXY_URL
    value: {{ index .Values "react-app-proxy-url" | quote }}
