global:
  domain: ifix-builds.psegs.in
cluster-configs:
  namespaces:
    create: false
    values: [ monitoring, jenkins ]
  root-ingress:
    namespace: jenkins
    serviceName: jenkins
    servicePort: 8080
    appRoot: ""
    cert-issuer: "letsencrypt-prod"

jenkins:
  persistence:
    enabled: true
    aws:
      - volumeId: "vol-049d6061d8f055c93"
        zone: ap-south-1b
  oauth:
    enabled: true
    acl:
      admin:
        - misdwss*devops-team
      user:
        - misdwss*mgramsewa-dev
        - misdwss*mgramsewa-uat
        - misdwss*mgramsewa-prod
        - misdwss*mgramsewa-qa

  jobBuilder:
    repos: >-
      'git@github.com:misdwss/iFix-Dev.git','git@github.com:misdwss/punjab-mgramseva.git'
  deploymentJobs:
    - name: ci
      acl: [misdwss*devops-team]
    - name: mgramseva-dev
      acl: [misdwss*mgramsewa-dev]
    - name: ifix-dev
      acl: [misdwss*mgramsewa-dev]  
    - name: mgramseva-qa
      acl: [misdwss*mgramsewa-qa, misdwss*mgramsewa-dev]  
    - name: pspcl-qa
      acl: [misdwss*mgramsewa-qa, misdwss*mgramsewa-dev]  
    - name: pspcl-ifix-uat
      acl: [misdwss*mgramsewa-uat,misdwss*mgramsewa-dev]
    - name: ifix-qa
      acl: [misdwss*mgramsewa-qa, misdwss*mgramsewa-dev]
    - name: mgramseva-uat
      acl: [misdwss*mgramsewa-uat]
    - name: ifix-uat
      acl: [misdwss*mgramsewa-uat]  
    - name: mgramseva-prod
      acl: [misdwss*mgramsewa-prod]
    - name: ifix-prod
      acl: [misdwss*mgramsewa-prod]

       
  master:
    ingress:
      enabled: true
    resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    javaOpts: "-Xms2560M -Xmx2560M -Duser.timezone=Asia/Calcutta"

nginx-ingress:
  replicas: 1
  default-backend-service: "jenkins/jenkins"
  namespace: jenkins
  cert-issuer: "letsencrypt-staging"
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "EECDH+CHACHA20:EECDH+AES"
  ssl-ecdh-curve: "X25519:prime256v1:secp521r1:secp384r1"
  controller:
    image:
      repository: egovio/nginx-ingress-controller
      tag: "0.26.1"

cert-manager:
  namespace: jenkins
  email: "devops-team@egov.org.in"

cluster-autoscaler:
  namespace: jenkins
  cloudProvider: aws  
  awsRegion: ap-south-1
  autoDiscovery:
    clusterName: egov-cicd
    tags:
    - kubernetes.io/cluster/ifix-cicd

postgres:
  namespace: jenkins
  postgresDatabase: ci_database
