global:
  domain: ifix-dwss.psegs.in
  containerRegistry: dwssio
  tracing-enabled: false
  namespace: pspcl
  nodepool:
    selector: ifix-prod-ng
    toleration: ifix-prod-ng

cluster-configs:
  namespaces:
    create: false
    values:
      [
        ifix,
        cert-manager,
        olap,
        pspcl
      ]

  rbac:
    - role: user
      namespaces: [pspcl]
    - role: admin
      namespaces: [pspcl]

  root-ingress:
    cert-issuer: letsencrypt-prod
  configmaps:
    egov-config:
      data:
        mongo-db-host: "ifix-db.cluster-cqqfmghbjssw.ap-south-1.docdb.amazonaws.com"
        mongo-db-name: "pspcl_qa_db"
        mongo-db-url: "mongodb://ifix-db.cluster-cqqfmghbjssw.ap-south-1.docdb.amazonaws.com:27017/?retryWrites=false"
        db-host: "magramsewa-prod-db.cvisvjyknxm1.ap-south-1.rds.amazonaws.com"
        db-name: "mgramseva_prod_db"
        keycloak-db-name: "keycloak_prod_db"
        db-url: "jdbc:postgresql://magramsewa-prod-db.cvisvjyknxm1.ap-south-1.rds.amazonaws.com/mgramseva_prod_db"
        domain: "ifix-dwss.psegs.in"
        egov-services-fqdn-name: "ifix-dwss.psegs.in/"
        egov-state-level-tenant-id: "pb"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/uat"
        kafka-brokers: "kafka-v2.pspcl:9092"
        kafka-infra-brokers: "kafka-v2-infra.pspcl:9092"
        logging-level-jdbc: "debug"
        serializers-timezone-in-ist: "true"
        server-tomcat-max-threads: "10"
        server-tomcat-max-connections: "500"
        spring-datasource-tomcat-initialSize: "1"
        spring-datasource-tomcat-max-active: "5"
        spring-jpa-show-sql: "true"
        tracer-errors-provideexceptionindetails: "true"
        timezone: "Asia/Kolkata"
        druid-host: "druid-broker.olap"

    egov-service-host:
      data:
        ifix-master-data-service: "http://ifix-master-data-service.ifix:8080/"
        fiscal-event-service: "http://fiscal-event-service.ifix:8080/"
        ifix-zuul: "http://ifix-zuul.ifix:8080/"
        ifix-department-entity-service: "http://ifix-department-entity-service.ifix:8080/"
        egov-mdms-service: "http://egov-mdms-service.mgramseva:8080/"



postgres:
  persistence:
    enabled: true
    azure:
      diskName: "postgres-db-0"
      diskUri: /subscriptions/71f67180-c7fb-43dd-988a-e9f9e3135adc/resourceGroups/MC_mgramsewa-qa_mgramsewa-qa_southeastasia/providers/Microsoft.Compute/disks/postgres-db-0
  postgresDatabase: mgramseva_prod_db

pspcl-ifix-adapter:
  pspcl-fetch-bill-url: "https://api.pspcl.in/Services/PunjabDWSS.svc"
  pspcl-fetch-payment-url: "https://api.pspcl.in/Services/PunjabDWSS.svc"
  keycloak-pspcl-credentials-clientid: "pspcl-ifix-uat"
  fiscal-event-tenantId: "pb"
  demand-coaCode: "2215-01-001-00-00-93"
  receipt-coaCode: "2215-01-001-00-00-93"
  fiscal-event-receiver: "mgramseva-uat"
  ifix-host: "https://ifix-dwss.psegs.in/"
  keycloak-host: "https://ifix-dwss.psegs.in/"
  java-enable-debug: "true"
  cron:
    schedule: "*/10 * * * *"
