cluster-configs:
  secrets:
    db:
      mongo-db-username: ENC[AES256_GCM,data:2GrFCo+QtBsFvlUo0A==,iv:8oDD7pPI7tGK5wrWMXqSyn0vx+LkDnAzd0J+C1u2bZw=,tag:0+PGx352k4hsEuNrqa5cYw==,type:str]
      mongo-db-password: ENC[AES256_GCM,data:HVs+grF+tOW4i9crtwquug==,iv:19DbUvjnQhw9JFmPUn3rSfGOdVPUWZMlZmkQR+DLeqU=,tag:lICCJZ/x7J00AngZnzEDxw==,type:str]
      mongo-db-authenticated-uri: ENC[AES256_GCM,data:3GQZ+eviaBwEvhngelfa1mzWkFw6dh/WZfI3sLlLGWqCI+yXRuo+GsPLTSVqIMdLlary1Qx7EYtjsuhswG8jVLCtfevyw2YISq5jYrJMKxC0hlzjc48qcS1zTHYWwPp4idYvX/G1zLL5yk7GBAfGhRezGrokF2fxjratuE/bQiOP+A==,iv:vdR9cqncEWjqo8NjDZxOq57kJe60Qh7GGFO97TiPdls=,tag:9xMZNGhenNrTXQ0pSqviIw==,type:str]
      username: ENC[AES256_GCM,data:yibRf33U9IPNObEEtaqu,iv:UYcPNp0eKcVMgYYbjIPS++HBaYu5DmH1pGS3xxXRaS8=,tag:lRTlDKhMiA/wgw7yKZ9/sA==,type:str]
      password: ENC[AES256_GCM,data:Mw9LKaSYX/xXVqmoiwq8OA==,iv:F7wbQ2JTiEzjmx3JuDvfHn4Z2pU/bqLxTwnbE9PNOP4=,tag:TdsuMLZVUTWAoB1P6l95yg==,type:str]
      pg-username: ENC[AES256_GCM,data:etTxLEgIo7WJg7sEKNy0,iv:s/bV+AKRq7E67T/WfZTogLy6tXYRCuomcDCEctaEyPY=,tag:3XUMMkxo+R5IJVh9GcasOQ==,type:str]
      pg-password: ENC[AES256_GCM,data:nmYJukMe+1ghAmgLoMRFrg==,iv:JMcVIQ/MvjxCL6loiKpWRwmOdg1ew/W+DF0RrkaV9ok=,tag:IFy/f37Bd3MKfCfjLJYoRg==,type:str]
      flywayUsername: ENC[AES256_GCM,data:1j4HdDfwUz7CZQKGxS1r,iv:8BL9QXcnL7e2L7u83lLSKMpigG2btfJOSlbJIlRZ698=,tag:UKmgRE8OcAVyvd6UkgvFPg==,type:str]
      flywayPassword: ENC[AES256_GCM,data:7qVr3mpEy9n5rbS7DIqo4g==,iv:Y2JKDr4wT62zf1QGQeyK2b1vqSfG056zZs26O+hxMa0=,tag:7Pou1nHiPyfBAX3FBeCdZw==,type:str]
      druid_username: ENC[AES256_GCM,data:gfx8CuypTx1+4xxUlNNxKg==,iv:BvjmVLFhXReStxv6lXnxPEBzhZqnYNRpxeh37BfTdZQ=,tag:hILhZNe9O8vKJOoTk1WasQ==,type:str]
      druid_password: ENC[AES256_GCM,data:S8AjosXZn82Hp2MbziSzpA==,iv:jlGjyKfaNVwrGBIrKcUA7t1DmtM8OFLIAW6ZPIsfLNA=,tag:DAE3E2IB2lmrS0TqoqlE7w==,type:str]
      druid_connect_uri: ENC[AES256_GCM,data:G4t/1/jmeQHAjdbmTn4vOi/STfOyZffrN46V7CfWSryul9Z02YOa7na4u+Ug65xsjBTYuiJ0nGobnanFQ6hbFmK6qJHhwcYQfCVHHWD8hcrNZSQ4axdPokEVL7OUdF11HQ==,iv:1+FMQFNXFFy+RGXd7bT2lKhIATJBdLD5OIfXUtDFpNc=,tag:CFcSO3PirTt4nCl9EYtr8Q==,type:str]
      metabase_connect_uri: ENC[AES256_GCM,data:Y1M5hk5MkOagMIXRBsIqGVT5TF63S6FqiKv0wEuvzniWuKloJNnhjagxzfpoX0M3vSs5ZPrE/pQpTAsk8QpetRrz8HoGpiLVSBAnrIsAdEWKZz3Ta+u9cQwya6l7zOybV+hsdcBD/KHsIP+JryM7Mwa+nAvgWAXPYA==,iv:lnNn2O+usiJziAhEo4h4rvYm1cWRHm6E+2OVMS5olus=,tag:As/2IGcZ+d6vlE+RpDIwGg==,type:str]
      druid_s3_accessKey: ENC[AES256_GCM,data:9v87sLogsCUT7F8U5k7UXi8cUIU=,iv:e9NCVS/NVpSem4OE/9ty6ecHleBFqgr2QCBULbnP11A=,tag:jZnpAt5Hz+mEH0zCL6+wDw==,type:str]
      druid_s3_secretKey: ENC[AES256_GCM,data:21qG7kRIS6xv//IYYgmhr8sxbgcXZm0SRrfBPANxLytN4g5Mnohm2w==,iv:gFyIQmAOKRjRa/RlQ5zL/a898BFVvraFG3ww6zahK9w=,tag:nKTbseHwkLnOI/P++X1F/g==,type:str]
      keycloak-username: ENC[AES256_GCM,data:i9YKTXwTa0sVs+9XGf2i3y9Wrg==,iv:TJaz/fzhkAggbNuHwridksIJrKy31xuV+P6vN0agGv0=,tag:miuDjJ3gB2HQvL8pu5yyKg==,type:str]
      keycloak-password: ENC[AES256_GCM,data:vz2bl32f//fJwQ==,iv:rURhHhEkebd1yvIt2lIeKnLyL7kseT0zCRkvhX5B9co=,tag:aPVNmD4i8DbJnQuzVSApYg==,type:str]
    keycloak-client-secrets:
      pspcl-keycloak-client-secret: ENC[AES256_GCM,data:aP63BH42n3VuEMJSLikK/gkA4qkHZLjVTwq3RDRhBsHl0qEs,iv:zaajdVFrEBr0t7tJ1IVz/1jctEXKw2uOkmshgGb4gOM=,tag:B0qA0Ffdprrfj1VqVmqOFw==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:ap-south-1:434036464328:key/2c94f2aa-a4a2-4c2e-9360-385e126d4b0c
      created_at: "2023-06-28T09:49:48Z"
      enc: AQICAHi4WY6M7pgB9kt1kp2GVWk7xEwjeYZytfl2nCXfbia9/QFVs52g4wtH+sZQLcBBqgvVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2NM04p3wYyF8+qStAgEQgDu4uJl5fEB82pjw6e/i99l0ObJWxX0k/CNyEjIsh1MDy47/GvK/ixTz9Ha3DpfKTL9oHvkNR0wAIPoq5A==
      aws_profile: ""
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-06-28T09:49:48Z"
  mac: ENC[AES256_GCM,data:r/+mAeW1j1EVGaFbPbK8ufpoHliaw8FtW/dd0Fnz/3n0S7/p1PYaL5GOLkhKb5gF2MBEEnXmkDXceBng00L2Os7+qhxU9YDUBZci2OLx4yF9ly0Z1adteQBfx0/hkfn1L3AT6JIqa0pIygWNWUa4vSLpHUcaofHMMwBJILcCz48=,iv:cntpCXUpss+0pIRVYjdxYN6UZiAH5kgOD8GQsTDNbeE=,tag:tvRob83/AbbiM91BzvuDSQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3