cluster-configs:
  secrets:
    db:
      mongo-db-username: ENC[AES256_GCM,data:8xHMifwYHooU1QHk5g==,iv:3wjIPu1me0dtNIuHzN7WJ7aLGU6pwCBRlxaLuks2jcQ=,tag:/KGXBObzP9g6pAApRMZ5Vg==,type:str]
      mongo-db-password: ENC[AES256_GCM,data:2sHIasw/dTTjAA0RDu1PkQ==,iv:nGR69m1LtJE3BBDPZP/QoPO6QF4xxOtKKVDVJYBQ15w=,tag:3ls2kipY/ZKPd6WHgpFXuA==,type:str]
      mongo-db-authenticated-uri: ENC[AES256_GCM,data:cabX1w8gtQx4OBtfYgC0MNtADw4hUoWqhw1fi/QN7BYRtC8ugf9Bk1aWXIfMEwsGtJJFsQRrtcbOkkBOgAKYxthjA7KrKz3dBxaBOA6WeCc2yNK1E9dtFTEKLvYDRO5KKAwrJsec36H2OMYxESWeOPcVYIiaRvC8sBW/jANnaPqdJQ==,iv:isGsgrJg/F5jlV8C4jEs4PUJYtw8Nvj7FLXfzv2Uzjg=,tag:jhVZANEDwCL3BlJtbCl5Ug==,type:str]
      username: ENC[AES256_GCM,data:TnrV3xXWzTBmnrqN/cwE,iv:SXcHP+SdpZ2mCSZvFAVNR38ctXJ7LF+iss5ZOpp8N7g=,tag:2ELQFX1/23GXGaZvqLqa7A==,type:str]
      password: ENC[AES256_GCM,data:OAUo09zlpFHQOzlbd0/2YA==,iv:VfNAA1krYyp0qONeVTP/YFYgNkzwY6RbQDkMTaMOLPc=,tag:Z/bFfjuC/UxszznTPgJwYg==,type:str]
      pg-username: ENC[AES256_GCM,data:P/XVSFSY0nzpOiX1lV6t,iv:YTpPe1lWKunISLK9qG3If2zqfMXGJatyDnNUn80S4Ac=,tag:Rh+JeUP3U1ZfJqiU+yew4g==,type:str]
      pg-password: ENC[AES256_GCM,data:m+Z5HVU2+LHXXaqOuuKSJw==,iv:bL/g/Icbg6/HKfQwv/h7uP+thQzgkVVpGyDaiuH0Q3M=,tag:j/3lo5rXzQQHzaEoqbPXLg==,type:str]
      flywayUsername: ENC[AES256_GCM,data:HH5tzhdottAcsXvSI80D,iv:F7CLdb/iA39O0o3GW7B/DpPLHavzA2bdtgrSOxEb3SQ=,tag:V7UejtbiVXSwkiDujJLi9w==,type:str]
      flywayPassword: ENC[AES256_GCM,data:lZLCB/NzgTSCGneHJA6A+w==,iv:QiZ7h1iajp3J5sSUGLwpFri/3+T+eEl/7b35rB75vDI=,tag:xYgPtTL1gsw4TLu99AJOOw==,type:str]
      druid_username: ENC[AES256_GCM,data:NLidXfnVfW9HPhEQ7wSAyQ==,iv:ckDIWz/W6m1t9uYBTvqKiAlGOO2HtXMmX98tknGzINw=,tag:A4H4PKGvwm2t34gjljC8KQ==,type:str]
      druid_password: ENC[AES256_GCM,data:e9WPuX8433yMhOAzcEd8Ig==,iv:gZlkjZSJePEYVzni3/liR2ogt6al5zF9NMy7iIIDcc8=,tag:AVfDXm2cgnlVs5/LL5kpLQ==,type:str]
      druid_connect_uri: ENC[AES256_GCM,data:QOxNvhU5ypoZyM4lr2dj6TG/6lg9EOCn1qK8+2Yi0pmZfdmI+/3/0wp+ZM2cMB6aE+00wPTy8loZq8qcxv1DRo4JE+nzor7eltO5Gt190oiujGCMTwPoUvK/yk9nSnzMDA==,iv:fTN/ip0K8fyb6yKkv8n81bTB6fFqpsScUQwSszQax3k=,tag:H4yE40EZLEEfekpJU8rT7g==,type:str]
      metabase_connect_uri: ENC[AES256_GCM,data:qcs+yyy/JGaEISdbdS1e65cuRlqJSHueoElNzDvVYCgHPrTCmgasLdJTWnKTPq+ZOJSKUY2dzUAU2NsYB8+2JW21piWJ3sNAHWQ74JTgwifDvZPD03XNlchYMyPnCagQ6XjWc/TzWfZ106vW1CPs0FeFBgGGIb3YUQ==,iv:/XVNLI6kUpuuc5uFOOt9Y9vE159REv53t+KjyY/zXZc=,tag:okTW3kfrVK7sRDBGo90Cow==,type:str]
      druid_s3_accessKey: ENC[AES256_GCM,data:ogYo2Tuqs6Osoawa6uUYfM7T8lE=,iv:5JWPbL/31M55cXeB8tmzpFr7szOU4qkYTGwRP4k83LM=,tag:hX3Hrfkvzs7bpVebAGDJDw==,type:str]
      druid_s3_secretKey: ENC[AES256_GCM,data:LnYqk18hDZ8PDSwtouyO4cpqWL+Lz0bFZuPERWNSOKBU9jDby66VQg==,iv:FesQG/Ptuye75gL6EJ7OEi9/i/yW8M31u9nJhJhoEL8=,tag:zZedTBfDJH0hWUPE8T6F3A==,type:str]
      keycloak-username: ENC[AES256_GCM,data:6pOmYYg0RvbaH/7DvXk61RpMeA==,iv:vMQMj44dJWQ1zVP0vIegpwMxXd2Ag94AioJGAEuBzs8=,tag:M1D3K+aByx08m3Skqu64DA==,type:str]
      keycloak-password: ENC[AES256_GCM,data:IZgVdN+59XMngw==,iv:RKM9x7M+Vq36MuwJAItqUzGwSl//P+OUbml335qcfF4=,tag:muPZcntt9PIW7klz6c9Sjg==,type:str]
    keycloak-client-secrets:
      oauth2-proxy:
        pspcl-keycloak-client-secret: 
sops:
  kms:
    - arn: arn:aws:kms:ap-south-1:434036464328:key/2c94f2aa-a4a2-4c2e-9360-385e126d4b0c
      created_at: "2021-11-19T10:33:04Z"
      enc: AQICAHi4WY6M7pgB9kt1kp2GVWk7xEwjeYZytfl2nCXfbia9/QFkLq+timzuenAtNAgyIeDYAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdcGfxpG0f1yDt2CDAgEQgDsHAGVymYzBtbZkhPJROGpbqtsRZpPirgMORvYTEhGPXHU4rKL6WxPvhTbRNEpQ1WoqOFlf0D/WIOtVXw==
      aws_profile: ""
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2021-11-24T06:15:01Z"
  mac: ENC[AES256_GCM,data:65+LqBg9fbE+VP4YgAfrHXPobc7pVYD5pT9bJmd308GcFmNkdhl/Nh2T2IlEikaBSJWkGC86vjXsgrY/M3xguJDt2cc0LhxYoiz97CpDsixmUxA1vT3qlmc4DQXJtQ9Wk0uh0DPjoDHGvEnQZKC35JqbzAJyzkPkHJRu4gHS2TM=,iv:MC83vla4GnM65lCxf6LxQigvV7VpyFlS9GUD0ggxf8I=,tag:PWChlgueYe/JprV5uhxkug==,type:str]
  pgp:
    - created_at: "2021-11-19T10:33:04Z"
      enc: |
        -----BEGIN PGP MESSAGE-----
        
        hQEMA+gtFIQvidpKAQf/YMJWXKCfuBvITOZaEoMc8QXkA2DN/37titZMI78KhQUn
        7I0uNphqfrRP6ZM73mOR4cIxiZY6VTuO39dfoc4/lw+7t5EntQSmUuRATLUsNAr1
        6O0isWUt/+G4ZEfIR8IkjkSLRoPPNlF9FlRbE8/dEvMuxhJ32n4SxcZ7+ORN/VNe
        5GbV8gWZrs0lHaPVezr0H0a/zb/ER0LlXsxZwwM3jLPYeq0DUrhOGjX+Z0MF3SIb
        vZft4pg2iDtREsmlj2qjiDsUNzPMVhd7L7umB8EH6mi8I2KyqcdM+hBT1n8qmHN0
        T0ySnQUmbGbSTvJjGfIUBUYG2gI84jgUmE0T5E6z5dJeAd56y7DY5m8lE1esgCZD
        WjBVGtjZWzw04pVhiTuCQStvKVzuzmYF6j0LCDLwKVoiNgQGfroduiay1SKp5Fxg
        xgIXWw+BVApBYzG+XhO7cNudqMNvfYg6at8irTSpIQ==
        =oezP
        -----END PGP MESSAGE-----
      fp: B9FF61E01273EDF7DE298B52F4D6BD77E5C66196
  unencrypted_suffix: _unencrypted
  version: 3.7.1
