{{- with index .Values "cluster-configs" "root-ingress" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  {{- if ne .appRoot ""}}
    nginx.ingress.kubernetes.io/app-root: /{{ .appRoot }}
  {{- end }}
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ index . "cert-issuer" }}
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  rules:
  - host: {{ $.Values.global.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .serviceName }}
          servicePort: {{ .servicePort }}
        path: /
  tls:
  - hosts:
    - {{ $.Values.global.domain }}
    secretName: {{ $.Values.global.domain }}-tls-certs         
{{- end -}}
