apiVersion: v1
kind: Secret
metadata:
  name: superset-{{ template "postgresql.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: postgresql
type: {{ .Values.postgresql.type }}
data:
  postgres-password: {{ .Values.postgresql.postgrespassword | quote }}
  password: {{ .Values.postgresql.password | quote }}