{{- with index .Values "cluster-configs" "secrets" "db" }}
{{- if index . "password" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "db" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: {{ index $.Values "cluster-configs" "secrets" "db" "username" | b64enc | quote }}
  password: {{ index $.Values "cluster-configs" "secrets" "db" "password" | b64enc | quote }}
  read-username: {{ index $.Values "cluster-configs" "secrets" "db" "read-username" | b64enc | quote }}
  read-password: {{ index $.Values "cluster-configs" "secrets" "db" "read-password" | b64enc | quote }}
  flyway-username: {{ index $.Values "cluster-configs" "secrets" "db" "flywayUsername" | b64enc | quote }}
  flyway-password: {{ index $.Values "cluster-configs" "secrets" "db" "flywayPassword" | b64enc | quote }}
  {{- if index $.Values "cluster-configs" "secrets" "db" "mongo-db-username" }}
  mongo-db-username: {{ index $.Values "cluster-configs" "secrets" "db" "mongo-db-username" | b64enc | quote }}
  mongo-db-password: {{ index $.Values "cluster-configs" "secrets" "db" "mongo-db-password" | b64enc | quote }}
  mongo-db-authenticated-uri: {{ index $.Values "cluster-configs" "secrets" "db" "mongo-db-authenticated-uri" | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

