{{- with index .Values "cluster-configs" "secrets" "elasticsearch-certificate" }}
{{- if and .esService .esNamespace }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "elasticsearch-certificate" "name" }}
  namespace: {{ $ns }}
data:
{{ ( include "elasticsearch.gen-certs" (dict "namespace" $ns "Values" .Values ) ) | indent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
