
{{- with index .Values "cluster-configs" "secrets" "keycloak"  }}
{{- if index . "keycloak-clientsecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  keycloak-clientsecret: {{ index . "keycloak-clientsecret" | b64enc | quote }}
{{- if index . "keycloak-pspcl-clientsecret" }}  
  keycloak-pspcl-clientsecret: {{ index . "keycloak-pspcl-clientsecret" | b64enc | quote }}
{{- end }} 
{{- if index . "oauth-mgramseva-password" }}
  oauth-mgramseva-password: {{ index . "oauth-mgramseva-password" | b64enc | quote }}   
{{- end }}  
{{- end }}
{{- end }}
