{{- if and (eq .Values.storage.type "elasticsearch") .Values.storage.elasticsearch.externalService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storage.elasticsearch.externalService.name }}
  namespace: monitoring
  labels:
    app: {{ .Values.storage.elasticsearch.externalService.name }}
spec:
  type: ExternalName
  externalName: {{ .Values.storage.elasticsearch.externalService.externalName }}
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: {{ .Values.storage.elasticsearch.externalService.name }}
{{- end -}}