# Common Labels
labels:
  app: "boundary-bulk-bff"
  group: "rainmaker"

namespace: egov

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "boundary-bulk-bff"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "boundary_bulk_bff_schema"
    image:
      repository: "boundary-bulk-bff-db"

# Container Configs
image:
  repository: "boundary-bulk-bff"
replicas: "1"

# Additional Container Envs
env: |
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers 
  - name: EGOV_FILESTORE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: FILE_STORE_SERVICE_END_POINT
    value: filestore/v1/files
  - name: EGOV_BOUNDARY_RELATIONSHIP_SEARCHPATH
    value: boundary-service/boundary-relationships/_search
  - name: EGOV_BOUNDARY_SERVICE_SEARCHPATH
    value: boundary-service/boundary/_search
  - name: EGOV_BOUNDARY_HIERARCHY_SEARCHPATH
    value: boundary-service/boundary-hierarchy-definition/_search
  - name: EGOV_BOUNDARY_ENTITY_SEARCHPATH
    value: boundary-service/boundary/_search
  - name: EGOV_BOUNDARY_ENTITY_CREATEPATH
    value: boundary-service/boundary/_create
  - name: "DB_URL"
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url

  - name: "SCHEMA_TABLE"
    value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}
  - name: "FLYWAY_USER"
    valueFrom:
      secretKeyRef:
          name: db
          key: flyway-username
  - name: "FLYWAY_PASSWORD"
    valueFrom:
      secretKeyRef: 
          name: db
          key: flyway-password
  - name: "FLYWAY_LOCATIONS"
    valueFrom: 
      configMapKeyRef: 
          name: egov-config
          key: flyway-locations
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password   
  - name: DB_PORT
    value: "5432"
  - name: DB_SCHEMA
    value: "public"
  - name: LOCALE
    value: {{ .Values.defaultLocale | default "en_IN" }} 
  - name: LOCALIZATION_MODULE
    value: "rainmaker-admin-schemas"
  - name: APP_LOG_LEVEL
    value: {{ .Values.logLevel | default "info" }} 
  - name: APP_MAX_DEBUG_CHAR
    value: "{{ .Values.maxDebugChar | default "500" }}"
    
  - name: CACHE_ENABLED
    value: "true"
  - name: RESET_CACHE
    value: "true"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_HOST
    value: "redis.backbone"
  - name: EGOV_HOST
    value: "https://mgramseva-uat.psegs.in/"
  - name: BOUNDARY_CODE_HEADER_NAME
    value: "BOUNDARY_CODE"
  - name: BOUNDARY_TAB_NAME
    value: "BOUNDARY_DATA"
