apiVersion: v1
kind: Service
metadata:
  name: superset-{{ template "postgresql.name" . }}-hl
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: postgresql
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: {{ .Values.spec.type }}
  clusterIP: {{ .Values.spec.clusterIP }}
  publishNotReadyAddresses: {{ .Values.spec.publishNotReadyAddresses }}
  ports:
    - name: tcp-postgresql
      port: {{ .Values.spec.port }}
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql