apiVersion: v1
kind: Service
metadata:
  name: superset-{{ template "postgresql.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: postgresql
spec:
  type: {{ .Values.spec.type }}
  ports:
    - name: tcp-postgresql
      port: {{ .Values.spec.port }}
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql