environments:
  uat:
    values:
      - namespace: monitoring
      - ../../environments/mgramseva-uat-secrets.yaml
      - ../../environments/mgramseva-uat.yaml
  prod:
    values:
      - namespace: monitoring
      - ../../environments/mgramseva-prod-secrets.yaml
      - ../../environments/mgramseva-prod.yaml
---

repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: jaegertracing
  url: https://jaegertracing.github.io/helm-charts

releases:

- name: loki-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/loki-stack
  version: 2.10.1
  values:
  - ./values/loki-stack.yaml
  - loki:
      persistence: {{ .Values.loki.persistence | toYaml | nindent 8 }}
      config:
        schema_config: {{ .Values.loki.schema_config | toYaml | nindent 10 }}
        storage_config: {{ .Values.loki.storage_config | toYaml | nindent 10 }}
        compactor: {{ .Values.loki.compactor | toYaml | nindent 10 }}
        limits_config: {{ .Values.loki.limits_config | toYaml | nindent 10 }}
        chunk_store_config: {{ .Values.loki.chunk_store_config | toYaml | nindent 10 }}
        table_manager: {{ .Values.loki.table_manager | toYaml | nindent 10 }}

