# Common Labels
labels:
  app: "ifix-es-pipeline"
  group: "ifix"

namespace: ifix

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_survey_services_schema"
    image:
      repository: "egov-survey-services-db"

# Container Configs
image:
  repository: "ifix-es-pipeline"
replicas: "1"

appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |  
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "ifix-fiscal-events"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: FISCAL_EVENT_KAFKA_PUSH_TOPIC
    value: {{ index .Values "fiscal-event-kafka-push-topic" | quote }}
  - name: IFIX_DEPARTMENT_ENTITY_SEARCH_ENDPOINT
    value: {{ index .Values "ifix-department-entity-search-endpoint" | quote }}
  - name: IFIX_DEPARTMENT_ENTITY_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: ifix-department-entity-service
