apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
metadata:
  name: superset-{{ include "redis.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: redis
