apiVersion: v1
kind: Service
metadata:
  name: superset-{{ template "redis.name" . }}-master
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: redis
spec:
  type: {{ .Values.spec.type }}
  ports:
    - name: tcp-redis
      port: {{ .Values.spec.port }}
      targetPort: redis
  selector:
    app.kubernetes.io/name: redis