apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: egov-filestore
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }} 
{{- else }}   
  namespace: {{ .Values.namespace }}
{{- end }}  
  annotations:
    kubernetes.io/ingress.class: "nginx"  
    nginx.ingress.kubernetes.io/proxy-body-size: 8m                          
spec:
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - backend:
          service:
            name: zuul
            port:
              number: 8080
        path: /{{ .Values.ingress.context }}  